from .uitvsfc_vocab import UIT_VSFC_Vocab_Topic, UIT_VSFC_Vocab_Sentiment
from .uit_victsd_vocab import UIT_ViCTSD_Vocab
from .uit_vifds_vocab import UIT_ViFDS_Vocab
from .uit_absa_vocab import UIT_ABSA_Vocab
from .vihos_vocab import ViHOS_Vocab
from .uit_vsmec_vocab import UIT_VSMEC_Vocab
from .uit_vihsd_vocab import UIT_ViHSD_Vocab
from .uit_viocd_vocab import UIT_ViOCD_label, UIT_ViOCD_domain
from .new_uitvsfcvocab_topic import UIT_VSFC_newVocab_Topic
from .new_uitvsfcvocab_sentiment import UIT_VSFC_newVocab_Sentiment
from .new_UITViOCDVocab_label import UIT_ViOCD_newVocab_label
from .new_UITOCDVocab_domain import UIT_ViOCD_newVocab_domain
from .new_ViNLIVocab import ViNLI_newVocab
from .new_UITViCTSDVocab_toxic import UIT_ViCTSD_newVocab_Toxic
from .new_UITViCTSDVocab_contruct import UIT_ViCTSD_newVocab_Construct
from .new_UITViSFDVocab_ABSA import UIT_ViSFD_newVocab_ABSA
from .new_ViHOSVocab import ViHOS_newVocab

from .phoner_vocab import PhoNER_Vocab
from .phobert_phoner_vocab import PhoBERT_PhoNER_Vocab
from .phobert_vihos_vocab import PhoBERT_ViHOS_Vocab
from .phobert_ocd_vocab_domain import PhoBERT_OCD_Vocab_Domain
from .phobert_ocd_vocab_label import PhoBERT_OCD_Vocab_Label