from .uitvsfc_vocab import UIT_VSFC_Vocab
from .new_uitvsfcvocab_topic import UIT_VSFC_newVocab_Topic
from .new_uitvsfcvocab_sentiment import UIT_VSFC_newVocab_Sentiment
from .new_UITViOCDVocab_label import UIT_ViOCD_newVocab_label
from .new_UITOCDVocab_domain import UIT_ViOCD_newVocab_domain
from .new_ViNLIVocab import ViNLI_newVocab