vocab:
  type: BPETokenizer_VSFC_Sentiment
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  schema: 1
  vocab_size: 230 # same as vipher
  model_prefix: "checkpoints/UIT_VFSC/sentiment/BiLSTM/BPE/vsfc_bpe"
  model_type: "bpe"
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 32
  num_workers: 4

model:
  name: BiLSTM_Model6layer_VSFC_BPE_Sentiment
  architecture: BiLSTM_Model
  layer_dim: 6
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.2
  output_dim: 3
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/UIT_VFSC/sentiment/BiLSTM/BPE"
  seed: 42
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: "f1"

task: RNN_Label_Task