from .text_classification import TextClassification
from .newVocabtest_task import NewVocabTest
from .newVocabOCD_task import NewOCDTest
from .mamba_ViNLI_task import MambaViNLITask
from .transformer_task_label import TransformerLabel
from .lstm_OCD_task_label import lstm_Label_Task
from .Rnn_OCD_task_label import rnn_Label_Task
from .GRU_task_label import GRU_Label_Task
from .NLI_task import NLI_Task
from .lstm_task_ABSA import lstm_ABSA_Task
