vocab:
  type: UnigramTokenizer_VSFC_Sentiment
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  schema: 1
  vocab_size: 230 # same as vipher
  model_prefix: "checkpoints/UIT_VFSC/sentiment/CNN/unigram/vsfc_unigram"
  model_type: "unigram"
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 32
  num_workers: 4

model:
  name: CNN_Model3kernel_VSFC_Unigram_Sentiment
  architecture: CNN_Model
  embed_dim: 300
  num_filters: 100
  d_model: 300
  dropout: 0.2
  output_dim: 3
  kernel_sizes: [2,3,4]
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/UIT_VFSC/sentiment/CNN/unigram"
  seed: 42
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: "f1"

task: RNN_Label_Task