vocab:
  type: UIT_ViOCD_label
  path:
    train: datasets/Dataset/UIT-ViOCD/train-segment.json
    dev: datasets/Dataset/UIT-ViOCD/dev-segment.json
    test: datasets/Dataset/UIT-ViOCD/test-segment.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_ViOCD_newDataset_Label
    path: datasets/Dataset/UIT-ViOCD/train-segment.json
  dev:
    type: UIT_ViOCD_newDataset_Label
    path: datasets/Dataset/UIT-ViOCD/dev-segment.json
  test: 
    type: UIT_ViOCD_newDataset_Label
    path: datasets/Dataset/UIT-ViOCD/test-segment.json
  batch_size: 32
  num_workers: 16

model:
  name: BiGRU_Model3layer_ViOCD_ws
  architecture: BiGRU_Model
  layer_dim: 3
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.1
  output_dim: 2
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.1
  warmup: 1000
  patience: 5
  score: f1

task: GRU_Label_Task
