vocab:
  type: UIT_VSMEC_Vocab
  path:
    train: datasets/Dataset/UIT-VSMEC/train.json
    dev: datasets/Dataset/UIT-VSMEC/dev.json
    test: datasets/Dataset/UIT-VSMEC/test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/train.json
  dev:
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/dev.json
  test: 
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/test.json
  batch_size: 32
  num_workers: 16

model:
  name: BiGRU_Model3layer_ViSMEC
  architecture: BiGRU_Model
  layer_dim: 3
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.1
  output_dim: 7
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 1
  warmup: 1000
  patience: 20
  score: f1

task: GRU_Label_Task
