vocab:
  type: UIT_ViFDS_Vocab
  path:
    train: datasets/Dataset/UIT-ViFDS/train.json
    dev: datasets/Dataset/UIT-ViFDS/dev.json
    test: datasets/Dataset/UIT-ViFDS/test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_ViFDS_Dataset_ABSA
    path: datasets/Dataset/UIT-ViFDS/train.json
  dev:
    type: UIT_ViFDS_Dataset_ABSA
    path: datasets/Dataset/UIT-ViFDS/dev.json
  test: 
    type: UIT_ViFDS_Dataset_ABSA
    path: datasets/Dataset/UIT-ViFDS/test.json
  batch_size: 32
  num_workers: 16

model:
  name: BiGRU_Model3layer_ViFDS
  architecture: BiGRU_Model_ABSA
  layer_dim: 3
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  output_dim: 4
  num_categories: 11
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.5
  warmup: 1000
  patience: 10
  score: f1

task: GRU_ABSA_Task
