vocab:
  type: UIT_VSMEC_Vocab
  path:
    train: datasets/Dataset/UIT-VSMEC/train.json
    dev: datasets/Dataset/UIT-VSMEC/dev.json
    test: datasets/Dataset/UIT-VSMEC/test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/train.json
  dev:
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/dev.json
  test: 
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/test.json
  batch_size: 32
  num_workers: 16

model:
  name: CNN_ViSMEC
  architecture: CNN_Model
  embed_dim: 300
  num_filters: 100
  d_model: 300
  dropout: 0.2
  output_dim: 7
  kernel_sizes: [3, 4, 5]
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.5
  warmup: 1000
  patience: 10
  score: f1

task: CNN_Label_Task
