vocab:
  type: UIT_ViOCD_label
  path:
    train: datasets/Dataset/UIT-ViOCD/train-segment.json
    dev: datasets/Dataset/UIT-ViOCD/dev-segment.json
    test: datasets/Dataset/UIT-ViOCD/test-segment.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_ViOCD_newDataset_Label
    path: datasets/Dataset/UIT-ViOCD/train-segment.json
  dev:
    type: UIT_ViOCD_newDataset_Label
    path: datasets/Dataset/UIT-ViOCD/dev-segment.json
  test: 
    type: UIT_ViOCD_newDataset_Label
    path: datasets/Dataset/UIT-ViOCD/test-segment.json
  batch_size: 32
  num_workers: 16

model:
  name: CNN_ViOCD_ws
  architecture: CNN_Model
  embed_dim: 300
  num_filters: 100
  d_model: 300
  dropout: 0.2
  output_dim: 7
  kernel_sizes: [2, 3, 4]
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.01
  warmup: 1000
  patience: 5
  score: f1

task: lstm_Label_Task
