vocab:
  type: UIT_ViFDS_Vocab
  path:
    train: datasets/Dataset/UIT-ViFDS/train.json
    dev: datasets/Dataset/UIT-ViFDS/dev.json
    test: datasets/Dataset/UIT-ViFDS/test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_ViFDS_Dataset_ABSA
    path: datasets/Dataset/UIT-ViFDS/train.json
  dev:
    type: UIT_ViFDS_Dataset_ABSA
    path: datasets/Dataset/UIT-ViFDS/dev.json
  test: 
    type: UIT_ViFDS_Dataset_ABSA
    path: datasets/Dataset/UIT-ViFDS/test.json
  batch_size: 32
  num_workers: 16

model:
  name: CNN_Model_ViFDS
  architecture: CNN_Model_ABSA
  embed_dim: 300
  num_filters: 100
  d_model: 300
  dropout: 0.2
  output_dim: 5
  kernel_sizes: [3, 4, 5]
  num_categories: 11
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.1
  warmup: 1000
  patience: 25
  score: f1

task: CNN_ABSA_Task
