vocab:
  type: UIT_VSFC_Vocab_Sentiment
  path:
    train: datasets/Dataset/UIT-VSFC/UIT-VSFC-train.json
    dev: datasets/Dataset/UIT-VSFC/UIT-VSFC-dev.json
    test: datasets/Dataset/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_VSFC_Dataset_Sentiment
    path: datasets/Dataset/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_VSFC_Dataset_Sentiment
    path: datasets/Dataset/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_VSFC_Dataset_Sentiment
    path: datasets/Dataset/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 32
  num_workers: 16

model:
  name: CNN_Model_VSFC_Sentiment
  architecture: CNN_Model
  embed_dim: 300
  num_filters: 100
  d_model: 300
  dropout: 0.2
  output_dim: 4
  kernel_sizes: [3, 4, 5]
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.1
  warmup: 1000
  patience: 10
  score: f1

task: CNN_Label_Task
