vocab:
  type: UIT_ViCTSD_Vocab
  path:
    train: datasets/Dataset/UIT-ViCTSD/train-segment.json
    dev: datasets/Dataset/UIT-ViCTSD/dev-segment.json
    test: datasets/Dataset/UIT-ViCTSD/test-segment.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_ViCTSD_Dataset_Construct
    path: datasets/Dataset/UIT-ViCTSD/train-segment.json
  dev:
    type: UIT_ViCTSD_Dataset_Construct
    path: datasets/Dataset/UIT-ViCTSD/dev-segment.json
  test: 
    type: UIT_ViCTSD_Dataset_Construct
    path: datasets/Dataset/UIT-ViCTSD/test-segment.json
  batch_size: 32
  num_workers: 16

model:
  name: CNN_Model_ViCTSD_Construct_ws
  architecture: CNN_Model
  embed_dim: 300
  num_filters: 100
  d_model: 300
  dropout: 0.2
  output_dim: 2
  kernel_sizes: [3, 4, 5]
  num_categories: 11
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.01
  warmup: 1000
  patience: 10
  score: f1

task: CNN_Label_Task
