vocab:
  type: BPE_ViSFD
  path:
    train: data/UIT-ViSFD/train.json
    dev: data/UIT-ViSFD/dev.json
    test: data/UIT-ViSFD/test.json
  min_freq: 5
  # required for the base vocab
  model_prefix: "checkpoints/LSTM_Model6layer_BPE_ViSFD_ABSA/LSTM_Model6layer_Unigram_ViSFD_ABSA/vsfc_unigram"
  model_type: "bpe"

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViSFD_Dataset_ABSA
    path: data/UIT-ViSFD/train.json
  dev:
    type: UIT_ViSFD_Dataset_ABSA
    path: data/UIT-ViSFD/dev.json
  test: 
    type: UIT_ViSFD_Dataset_ABSA
    path: data/UIT-ViSFD/test.json
  batch_size: 32
  num_workers: 4

model:
  name: LSTM_Model6layer_BPE_ViSFD_ABSA
  architecture: LSTM_Model_ABSA
  layer_dim: 6
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.2
  output_dim: 5
  num_categories: 12
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/LSTM_Model6layer_BPE_ViSFD_ABSA"
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: f1

task: lstm_ABSA_Task
