vocab:
  type: UIT_ViOCD_newVocab_domain
  path:
    train: data/UIT-ViOCD/train.json
    dev: data/UIT-ViOCD/dev.json
    test: data/UIT-ViOCD/test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViOCD_newDataset_Domain
    path: data/UIT-ViOCD/train.json
  dev:
    type: UIT_ViOCD_newDataset_Domain
    path: data/UIT-ViOCD/dev.json
  test: 
    type: UIT_ViOCD_newDataset_Domain
    path: data/UIT-ViOCD/test.json
  batch_size: 4
  num_workers: 4

model:
  name: MambaClassificationOCDDomain
  architecture: MambaClassificationOCDDomain
  n_layers: 4
  d_state: 16
  d_conv: 4 # kernal size
  d_model: 171
  dropout: 0.3
  expand: 2 # expand factor
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/DomainNewVocab"
  learning_rate: 8e-3
  warmup: 1000
  patience: 50
  score: f1

task: MambaOCD_Domain_Task
