vocab:
  type: UnigramTokenizer_ViCTSD_Toxic
  path:
    train: data/UIT-ViCTSD/train.json 
    dev: data/UIT-ViCTSD/dev.json
    test: data/UIT-ViCTSD/test.json
  min_freq: 5
  # required for the base vocab


  model_prefix: "checkpoints/LSTM_Model6Layer_ViCTSD_Unigram_Toxic/LSTM_Model6Layer_ViCTSD_Unigram_Toxic/victsd_unigram"
  model_type: "unigram"

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViCTSD_Dataset_Toxic
    path: data/UIT-ViCTSD/train.json 
  dev:
    type: UIT_ViCTSD_Dataset_Toxic
    path: data/UIT-ViCTSD/dev.json
  test: 
    type: UIT_ViCTSD_Dataset_Toxic
    path: data/UIT-ViCTSD/test.json
  batch_size: 32
  num_workers: 4



model:
  name: LSTM_Model6Layer_ViCTSD_Unigram_Toxic
  architecture: LSTM_Model
  layer_dim: 6
  input_dim: 512
  hidden_dim: 512
  d_model: 512
  dropout: 0.2
  output_dim: 2
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/LSTM_Model6Layer_ViCTSD_Unigram_Toxic"
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: f1

task: lstm_Label_Task
