vocab:
  type: UIT_ViOCD_newVocab_label
  path:
    train: data/UIT-ViOCD/train.json
    dev: data/UIT-ViOCD/dev.json
    test: data/UIT-ViOCD/test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViOCD_newDataset_Label
    path: data/UIT-ViOCD/train.json
  dev:
    type: UIT_ViOCD_newDataset_Label
    path: data/UIT-ViOCD/dev.json
  test: 
    type: UIT_ViOCD_newDataset_Label
    path: data/UIT-ViOCD/test.json
  batch_size: 32
  num_workers: 4

model:
  name: Roformer6layer_Vipher_OCD_Label
  architecture: RoformerModel_vipher
  nlayers: 6
  head: 8
  d_model: 100
  hidden_dim : 512
  emb_dim : 512
  d_q: 64
  d_kv: 64
  d_ff: 2048
  output_dim: 2
  dropout: 0.5
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/Roformer6layer_Vipher_OCD_Label"
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: f1

task: TransformerLabel
