vocab:
  type: UIT_VSFC_newVocab
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViSFC_newDataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_ViSFC_newDataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_ViSFC_newDataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 4
  num_workers: 4

model:
  name: MambaClassification
  architecture: MambaClassification
  n_layers: 4
  d_state: 16
  d_conv: 4 # kernal size
  d_model: 171
  dropout: 0.3
  expand: 2 # expand factor
  label_smoothing: 0.5
  device: cuda


training:
  checkpoint_path: "checkpoints/TopicNewVocab"
  learning_rate: 8e-3
  warmup: 1000
  patience: 5
  score: f1

task: MambaTask
