vocab:
  type: ViNLI_newVocab
  path:
    train: data/VNLI/train.json
    dev: data/VNLI/dev.json
    test: data/VNLI/test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: NLI_Dataset
    path: data/VNLI/train.json
  dev:
    type: NLI_Dataset
    path: data/VNLI/dev.json
  test: 
    type: NLI_Dataset
    path: data/VNLI/test.json
  batch_size: 16
  num_workers: 4


model:
  name: GRU_Model6layer_VSFC_Topic
  architecture: GRU_Vipher
  layer_dim: 6
  input_dim: 513
  hidden_dim: 513
  d_model: 171
  dropout: 0.2
  output_dim: 5
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/LSTM_Model6layer_ViNLI"
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: f1

task: NLI_Task

