vocab:
  type: UIT_ViSFD_newVocab_ABSA
  path:
    train: data/UIT-ViSFD/train.json
    dev: data/UIT-ViSFD/dev.json
    test: data/UIT-ViSFD/test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViFDS_Dataset_ABSA
    path: data/UIT-ViSFD/train.json
  dev:
    type: UIT_ViFDS_Dataset_ABSA
    path: data/UIT-ViSFD/dev.json
  test: 
    type: UIT_ViFDS_Dataset_ABSA
    path: data/UIT-ViSFD/test.json
  batch_size: 32
  num_workers: 32

model:
  name: GRU_Model6layer_ViSFD_ABSA
  architecture: GRU_Vipher_ABSA
  layer_dim: 3
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  output_dim: 4
  num_categories: 11
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.1
  warmup: 1000
  patience: 15
  score: f1

task: GRU_ABSA_Task
