vocab:
  type: UIT_VSFC_newVocab_Sentiment
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViSFC_newDataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_ViSFC_newDataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_ViSFC_newDataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 4
  num_workers: 4


model:
  name: RNNModel6layer_VSFC_Sentiment
  architecture: RNNModel
  layer_dim: 6
  input_dim: 513
  hidden_dim: 513
  d_model: 171
  dropout: 0.2
  output_dim: 3
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/RNNModel6layer_VSFC_Sentiment"
  learning_rate: 0.1
  warmup: 1000
  patience: 5
  score: f1

task: rnn_Label_Task
