vocab:
  type: ViNLI_newVocab
  path:
    train: data/VNLI/train.json
    dev: data/VNLI/dev.json
    test: data/VNLI/test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: ViNLI_newDataset_Topic
    path: data/VNLI/train.json
  dev:
    type: ViNLI_newDataset_Topic
    path: data/VNLI/dev.json
  test: 
    type: ViNLI_newDataset_Topic
    path: data/VNLI/test.json
  batch_size: 16
  num_workers: 4

model:
  name: MambaNLI
  architecture: MambaNLI
  n_layers: 12
  d_state: 16
  d_conv: 4 # kernal size
  d_model: 171
  dropout: 0.5
  expand: 2 # expand factor
  label_smoothing: 0.5
  device: cuda


training:
  checkpoint_path: "checkpoints/testMambaNLI"
  learning_rate: 8e-3
  warmup: 1000
  patience: 5
  score: f1

task: MambaViNLITask
