vocab:
  type: BPE_Vietnamese_VSFC_Topic
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  # required for the base vocab

  
  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>


dataset:
  train: 
    type: UIT_ViSFC_Dataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_ViSFC_Dataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_ViSFC_Dataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 32
  num_workers: 4


model:
  name: GRU_Model6layer_VSFC_BPE_Topic
  architecture: GRU_Model
  layer_dim: 6
  input_dim: 512
  hidden_dim: 512
  d_model: 512
  dropout: 0.2
  output_dim: 4
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/GRU_Model6layer_VSFC_BPE_Topic"
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: f1

task: GRU_Label_Task
