vocab:
  type: BPE_ViSFD
  path:
    train: data/UIT-ViSFD/train.json
    dev: data/UIT-ViSFD/dev.json
    test: data/UIT-ViSFD/test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViFDS_Dataset_ABSA
    path: data/UIT-ViSFD/train.json
  dev:
    type: UIT_ViFDS_Dataset_ABSA
    path: data/UIT-ViSFD/dev.json
  test: 
    type: UIT_ViFDS_Dataset_ABSA
    path: data/UIT-ViSFD/test.json
  batch_size: 32
  num_workers: 4

model:
  name: CNN_Model6layer_BPE_ViSFD_ABSA
  architecture: CNN_Model_ABSA
  embed_dim: 300
  num_filters: 100
  d_model: 300
  dropout: 0.2
  output_dim: 5
  kernel_sizes: [3, 4, 5]
  num_categories: 11
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/CNN_Model6layer_BPE_ViSFD_ABSA"
  learning_rate: 0.1
  warmup: 1000
  patience: 25
  score: f1

task: CNN_ABSA_Task
