vocab:
  type: UnigramTokenizer_OCD_Domain
  path:
    train: data/UIT-ViOCD/train.json
    dev: data/UIT-ViOCD/dev.json
    test: data/UIT-ViOCD/test.json
  min_freq: 5
  # required for the base vocab


  model_prefix: "checkpoints/BiLSTM_vipher_OCD_Domain_6_layers/BiLSTM_vipher_OCD_Domain_6_layers/ocd_unigram"
  model_type: "unigram"

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViOCD_newDataset_Domain
    path: data/UIT-ViOCD/train.json
  dev:
    type: UIT_ViOCD_newDataset_Domain
    path: data/UIT-ViOCD/dev.json
  test: 
    type: UIT_ViOCD_newDataset_Domain
    path: data/UIT-ViOCD/test.json
  batch_size: 32
  num_workers: 4

model:
  name: BiLSTM_vipher_OCD_Domain_6_layers
  architecture: BiLSTM_Model_Vipher
  layer_dim: 6
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.2
  output_dim: 4
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/BiLSTM_vipher_OCD_Domain_6_layers"
  learning_rate: 0.1
  warmup: 1000
  patience: 25
  score: f1

task: lstm_Label_Task