vocab:
  type: WordPieceTokenizer_ViCTSD_Construct
  path:
    train: data/UIT-ViCTSD/train.json 
    dev: data/UIT-ViCTSD/dev.json
    test: data/UIT-ViCTSD/test.json
  min_freq: 5
  # required for the base vocab


  model_prefix: "checkpoints/GRU_Model6Layer_ViCTSD_WordPiece_Constructiveness"
  model_type: "word"

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViCTSD_Dataset_Construct
    path: data/UIT-ViCTSD/train.json 
  dev:
    type: UIT_ViCTSD_Dataset_Construct
    path: data/UIT-ViCTSD/dev.json
  test: 
    type: UIT_ViCTSD_Dataset_Construct
    path: data/UIT-ViCTSD/test.json
  batch_size: 32
  num_workers: 4



model:
  name: GRU_Model6Layer_ViCTSD_WordPiece_Constructiveness
  architecture: GRU_Model
  layer_dim: 6
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.2
  output_dim: 2
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/GRU_Model6Layer_ViCTSD_WordPiece_Constructiveness"
  learning_rate: 0.012915
  warmup: 1000
  patience: 50
  average: micro
  score: f1

task: GRU_Label_Task