vocab:
  type: UIT_ViCTSD_newVocab_Toxic
  path:
    train: data/UIT-ViCTSD/train.json
    dev: data/UIT-ViCTSD/dev.json
    test: data/UIT-ViCTSD/test.json
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViCTSD_Dataset_Toxic
    path: data/UIT-ViCTSD/train.json
  dev:
    type: UIT_ViCTSD_Dataset_Toxic
    path: data/UIT-ViCTSD/dev.json
  test: 
    type: UIT_ViCTSD_Dataset_Toxic
    path: data/UIT-ViCTSD/test.json
  batch_size: 32
  num_workers: 4

model:
  name: CNN_Model6layer_vipher_ViCTSD_Toxic
  architecture: CNN_Model_Vipher
  embed_dim: 300
  num_filters: 100
  d_model: 100
  kernel_sizes: [3, 4, 5]
  dropout: 0.2
  output_dim: 2
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/CNN_Model6layer_vipher_ViCTSD_Toxic"
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: f1

task: CNN_Label_Task