vocab:
  type: UIT_VSFC_newVocab
  path:
    train: data/UIT-VSFC/train.csv
    dev: data/UIT-VSFC/dev.csv
    test: data/UIT-VSFC/test.csv
  min_freq: 5
  # required for the base vocab

  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>

dataset:
  train: 
    type: UIT_ViSFC_newDataset_Topic
    path: data/UIT-VSFC/train.csv
  dev:
    type: UIT_ViSFC_newDataset_Topic
    path: data/UIT-VSFC/dev.csv
  test: 
    type: UIT_ViSFC_newDataset_Topic
    path: data/UIT-VSFC/test.csv
  batch_size: 32
  num_workers: 4

model:
  name: MambaClassification
  architecture: MambaClassification
  n_layers: 12
  d_state: 16
  d_conv: 4 # kernal size
  d_model: 512
  dropout: 0.5
  expand: 2 # expand factor
  label_smoothing: 0.5
  device: cuda


training:
  checkpoint_path: "checkpoints/testVocab"
  learning_rate: 0.1
  warmup: 1000
  patience: 5
  score: f1

task: MambaTask
