vocab:
  type: UnigramTokenizer_VSFC_Sentiment
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  # required for the base vocab

  model_prefix: "checkpoints/LSTM_Model6layer_VSFC_Unigram_Sentiment/LSTM_Model6layer_VSFC_Unigram_Sentiment/vsfc_unigram"
  model_type: "unigram"


  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>


dataset:
  train: 
    type: UIT_ViSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_ViSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_ViSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 4
  num_workers: 4


model:
  name: LSTM_Model6layer_VSFC_Unigram_Sentiment
  architecture: LSTM_Model
  layer_dim: 6
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.2
  output_dim: 3
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/LSTM_Model6layer_VSFC_Unigram_Sentiment"
  learning_rate: 0.1
  warmup: 1000
  patience: 50
  score: f1

task: lstm_Label_Task
