vocab:
  type: WordPieceTokenizer_VSFC_Sentiment
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  # required for the base vocab

  model_prefix: "checkpoints/GRU_Model6layer_VSFC_WordPiece_Sentiment/GRU_Model6layer_VSFC_WordPiece_Sentiment/vsfc_wordpiece"
  model_type: "word"


  eos_token: <e>
  unk_token: <u>
  pad_token: <p>
  bos_token: <b>
  space_token: <s>


dataset:
  train: 
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_VSFC_Dataset_Sentiment
    path: data/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 4
  num_workers: 4


model:
  name: GRU_Model6layer_VSFC_WordPiece_Sentiment
  architecture: GRU_Model
  layer_dim: 6
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  dropout: 0.2
  output_dim: 3
  label_smoothing: 0.5
  device: cuda

training:
  checkpoint_path: "checkpoints/GRU_Model6layer_VSFC_WordPiece_Sentiment"
  learning_rate: 0.012915
  warmup: 1000
  patience: 50
  average: micro
  score: f1

task: GRU_Label_Task