vocab:
  type: UIT_ABSA_Vocab
  path:
    train: datasets/Dataset/UIT-ABSA/Hotel_ABSA/train.json
    dev: datasets/Dataset/UIT-ABSA/Hotel_ABSA/dev.json
    test: datasets/Dataset/UIT-ABSA/Hotel_ABSA/test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_ABSA_Dataset
    path: datasets/Dataset/UIT-ABSA/Hotel_ABSA/train.json
  dev:
    type: UIT_ABSA_Dataset
    path: datasets/Dataset/UIT-ABSA/Hotel_ABSA/dev.json
  test: 
    type: UIT_ABSA_Dataset
    path: datasets/Dataset/UIT-ABSA/Hotel_ABSA/test.json
  batch_size: 32
  num_workers: 16

model:
  name: LSTM_Model3layer_UIT_ABSA_Hotel
  architecture: LSTM_Model_ABSA
  layer_dim: 3
  input_dim: 256
  hidden_dim: 256
  d_model: 256
  output_dim: 3
  num_categories: 34
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 1.
  warmup: 1000
  patience: 10
  score: f1

task: lstm_ABSA_Task
