vocab:
  type: PhoBERT_PhoNER_Vocab
  path:
    train: datasets/Dataset/PhoNER/train.json
    dev: datasets/Dataset/PhoNER/dev.json
    test: datasets/Dataset/PhoNER/test.json
  pretrained_name: vinai/phobert-large

dataset:
  train: 
    type: PhoNER
    path: datasets/Dataset/PhoNER/train.json
  dev:
    type: PhoNER
    path: datasets/Dataset/PhoNER/dev.json
  test: 
    type: PhoNER
    path: datasets/Dataset/PhoNER/test.json
  batch_size: 16
  num_workers: 16

model:
  name: PhoBERT_large_PhoNER
  architecture: Phobert_Sequential_Labeling
  pretrained_name: vinai/phobert-large
  freeze_pretrain: False
  output_dim: 11
  d_model: 1024
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.02
  warmup: 1000
  patience: 5
  score: f1

task: Transformer_Seq_labeling_Task
