vocab:
  type: PhoBERT_OCD_Vocab_Label
  path:
    train: data/UIT-ViOCD/train.json
    dev: data/UIT-ViOCD/dev.json
    test: data/UIT-ViOCD/test.json
  pretrained_name: vinai/phobert-base

dataset:
  train: 
    type: UIT_ViOCD_newDataset_Label
    path: data/UIT-ViOCD/train.json
  dev:
    type: UIT_ViOCD_newDataset_Label
    path: data/UIT-ViOCD/dev.json
  test: 
    type: UIT_ViOCD_newDataset_Label
    path: data/UIT-ViOCD/test.json
  batch_size: 32
  num_workers: 16

model:
  name: PhoBERT_base_OCD_Label
  architecture: Phobert_label
  pretrained_name: vinai/phobert-base
  freeze_pretrain: False
  output_dim: 2
  d_model: 768
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.005
  warmup: 1000
  patience: 20
  score: f1

task: Pretrained_TransformerLabel
