vocab:
  type: PhoBERT_ViCTSD_Vocab_Construct
  path:
    train: data/UIT-ViCTSD/train.json 
    dev: data/UIT-ViCTSD/dev.json
    test: data/UIT-ViCTSD/test.json
  pretrained_name: vinai/phobert-base

dataset:
  train: 
    type: UIT_ViCTSD_Dataset_Construct
    path: data/UIT-ViCTSD/train.json 
  dev:
    type: UIT_ViCTSD_Dataset_Construct
    path: data/UIT-ViCTSD/dev.json
  test: 
    type: UIT_ViCTSD_Dataset_Construct
    path: data/UIT-ViCTSD/test.json
  batch_size: 32
  num_workers: 4

model:
  name: PhoBERT_base_ViCTSD_Construct
  architecture: Phobert_label
  pretrained_name: vinai/phobert-base
  freeze_pretrain: False
  output_dim: 2
  d_model: 768
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.005
  warmup: 1000
  patience: 20
  score: f1

task: Transformer_Seq_labeling_Task
