vocab:
  type: UIT_VSMEC_Vocab
  path:
    train: datasets/Dataset/UIT-VSMEC/train.json
    dev: datasets/Dataset/UIT-VSMEC/dev.json
    test: datasets/Dataset/UIT-VSMEC/test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/train.json
  dev:
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/dev.json
  test: 
    type: UIT_VSMEC
    path: datasets/Dataset/UIT-VSMEC/test.json
  batch_size: 32
  num_workers: 32

model:
  name: Transformer_Model3layer_UIT_VSMEC
  architecture: TransformerModel
  nlayers: 3
  head: 8
  d_model: 512
  hidden_dim : 512
  emb_dim : 512
  d_q: 64
  d_kv: 64
  d_ff: 2048
  output_dim: 7
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints/Transformer_Model3layer_UIT_VSMEC"
  learning_rate: 0.05
  warmup: 1000
  patience: 10
  score: f1

task: TransformerLabel
