vocab:
  type: PhoNER_Vocab
  path:
    train: datasets/Dataset/PhoNER/train-segmented.json
    dev: datasets/Dataset/PhoNER/dev-segmented.json
    test: datasets/Dataset/PhoNER/test-segmented.json
  min_freq: 3
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: PhoNER
    path: datasets/Dataset/PhoNER/train-segmented.json
  dev:
    type: PhoNER
    path: datasets/Dataset/PhoNER/dev-segmented.json
  test: 
    type: PhoNER
    path: datasets/Dataset/PhoNER/test-segmented.json
  batch_size: 32
  num_workers: 16

model:
  name: Transformer_Model3layer_PhoNER_ws
  architecture: Transformer_seq_label
  nlayers: 3
  head: 8
  d_model: 512
  hidden_dim : 512
  emb_dim : 512
  d_q: 64
  d_kv: 64
  d_ff: 2048
  output_dim: 11
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.5
  warmup: 1000
  patience: 5
  score: f1

task: Transformer_Seq_labeling_Task
