vocab:
  type: UIT_VSFC_Vocab_Sentiment
  path:
    train: datasets/Dataset/UIT-VSFC/UIT-VSFC-train.json
    dev: datasets/Dataset/UIT-VSFC/UIT-VSFC-dev.json
    test: datasets/Dataset/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 3
  cls_token: <cls>
  unk_token: <unk>
  pad_token: <pad>
  bos_token: <bos>

dataset:
  train: 
    type: UIT_VSFC_Dataset_Sentiment
    path: datasets/Dataset/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_VSFC_Dataset_Sentiment
    path: datasets/Dataset/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_VSFC_Dataset_Sentiment
    path: datasets/Dataset/UIT-VSFC/UIT-VSFC-test.json
  batch_size: 32
  num_workers: 16

model:
  name: ViWordFormer_Model3layer_VSFC_Sentiment
  architecture: ViWordFormer
  nlayers: 3
  head: 8
  d_model: 512
  hidden_dim : 512
  emb_dim : 512
  d_q: 64
  d_kv: 64
  d_ff: 2048
  output_dim: 4
  dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.02
  warmup: 1000
  patience: 10
  score: f1

task: TransformerLabel
