vocab:
  type: UIT_VSFC_Vocab
  path:
    train: data/UIT-VSFC/UIT-VSFC-train.json
    dev: data/UIT-VSFC/UIT-VSFC-dev.json
    test: data/UIT-VSFC/UIT-VSFC-test.json
  min_freq: 5
  # required for the base vocab
  bos_token: <s>
  eos_token: </s>
  unk_token: <u>
  pad_token: <p>

dataset:
  train: 
    type: UIT_ViSFC_Dataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-train.json
  dev:
    type: UIT_ViSFC_Dataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-dev.json
  test: 
    type: UIT_ViSFC_Dataset_Topic
    path: data/UIT-VSFC/UIT-VSFC-test.json

model:
  nlayers: 3
  head: 8
  d_model: 512
  d_q: 64
  d_kv: 64
  d_ff: 2048
  dropout: 0.5
  label_smoothing: 0.5

training:
  learning_rate: 0.01
  patient: 5
